name: CI/CD Python ðŸ dpackage
on: push

jobs:
  ci:
    name: CI steps
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        #python: [3.6, 3.7, 3.8, 3.9]
        script: [lint, test, mypy]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install development requirements
      run: >-
        python -m
        pip install
        -r requirements-dev.txt
        --user
    - name: Run script ${{ matrix.script }}
      run: scripts/${{ matrix.script }}.sh
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

  cd:
    needs: ci
    name: CD to to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install development requirements
      run: >-
        python -m
        pip install
        -r requirements-dev.txt
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution ðŸ“¦ to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution ðŸ“¦ to PyPII
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

