name: Publish Python ðŸ distributions ðŸ“¦ to PyPI and TestPyPI
on: push

jobs:
  ci:
    name: CI steps
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        #python: [3.6, 3.7, 3.8, 3.9]
        script: [lint, test, mypy]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install development requirements
      run: >-
        python -m
        pip install
        -r requirements-dev.txt
        --user
    - name: Run script ${{ matrix.script }}
      run: scripts/${{ matrix.script }}.sh
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

